# Generated by Django 5.1 on 2024-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpq_author', '0001_initial'),
        ('fpq_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('author', 'phrase'), name='Quote of author'),
        ),
    ]
