# Generated by Django 5.1 on 2024-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpq_quote', '0002_quote_quote_of_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phrase',
            field=models.CharField(max_length=100),
        ),
    ]
