# Generated by Django 5.1 on 2024-08-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpq_quote', '0003_alter_quote_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phrase',
            field=models.CharField(max_length=200),
        ),
    ]
