# Generated by Django 5.1 on 2024-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpq_quote', '0004_alter_quote_phrase'),
        ('fpq_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(to='fpq_tag.tag'),
        ),
    ]
