# Generated by Django 5.1 on 2024-09-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpq_quote', '0006_alter_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phrase',
            field=models.CharField(max_length=1300),
        ),
    ]
